// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countConversationsByUserID = `-- name: CountConversationsByUserID :one
SELECT COUNT(*)
FROM chat_schema.conversations c
INNER JOIN chat_schema.conversation_members cm ON cm.conversation_id = c.id
WHERE cm.user_id = $1
`

func (q *Queries) CountConversationsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO chat_schema.conversations (type, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, type, name, created_by, created_at, updated_at
`

type CreateConversationParams struct {
	Type      string    `json:"type"`
	Name      *string   `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (ChatSchemaConversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Type, arg.Name, arg.CreatedBy)
	var i ChatSchemaConversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDMConversation = `-- name: FindDMConversation :one
SELECT c.id, c.type, c.name, c.created_by, c.created_at, c.updated_at
FROM chat_schema.conversations c
WHERE c.type = 'dm'
  AND c.id IN (
      SELECT cm1.conversation_id FROM chat_schema.conversation_members cm1 WHERE cm1.user_id = $1
  )
  AND c.id IN (
      SELECT cm2.conversation_id FROM chat_schema.conversation_members cm2 WHERE cm2.user_id = $2
  )
`

type FindDMConversationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

// Find an existing DM between exactly two users
func (q *Queries) FindDMConversation(ctx context.Context, arg FindDMConversationParams) (ChatSchemaConversation, error) {
	row := q.db.QueryRow(ctx, findDMConversation, arg.UserID, arg.UserID_2)
	var i ChatSchemaConversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, name, created_by, created_at, updated_at
FROM chat_schema.conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (ChatSchemaConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i ChatSchemaConversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByUserID = `-- name: ListConversationsByUserID :many
SELECT c.id, c.type, c.name, c.created_by, c.created_at, c.updated_at
FROM chat_schema.conversations c
INNER JOIN chat_schema.conversation_members cm ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListConversationsByUserID(ctx context.Context, arg ListConversationsByUserIDParams) ([]ChatSchemaConversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSchemaConversation{}
	for rows.Next() {
		var i ChatSchemaConversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
