// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addConversationMember = `-- name: AddConversationMember :one
INSERT INTO chat_schema.conversation_members (conversation_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, user_id, role, joined_at
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (ChatSchemaConversationMember, error) {
	row := q.db.QueryRow(ctx, addConversationMember, arg.ConversationID, arg.UserID, arg.Role)
	var i ChatSchemaConversationMember
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countConversationMembers = `-- name: CountConversationMembers :one
SELECT COUNT(*) FROM chat_schema.conversation_members
WHERE conversation_id = $1
`

func (q *Queries) CountConversationMembers(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationMembers, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT id, conversation_id, user_id, role, joined_at
FROM chat_schema.conversation_members
WHERE conversation_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID uuid.UUID) ([]ChatSchemaConversationMember, error) {
	rows, err := q.db.Query(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSchemaConversationMember{}
	for rows.Next() {
		var i ChatSchemaConversationMember
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM chat_schema.conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.ConversationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
    SELECT 1 FROM chat_schema.conversation_members
    WHERE conversation_id = $1 AND user_id = $2
) AS is_member
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
