// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_schema.messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, is_edited, is_deleted, created_at, updated_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatSchemaMessage, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i ChatSchemaMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastMessage = `-- name: GetLastMessage :one
SELECT id, conversation_id, sender_id, content, is_edited, is_deleted, created_at, updated_at
FROM chat_schema.messages
WHERE conversation_id = $1
  AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastMessage(ctx context.Context, conversationID uuid.UUID) (ChatSchemaMessage, error) {
	row := q.db.QueryRow(ctx, getLastMessage, conversationID)
	var i ChatSchemaMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, sender_id, content, is_edited, is_deleted, created_at, updated_at
FROM chat_schema.messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (ChatSchemaMessage, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i ChatSchemaMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, content, is_edited, is_deleted, created_at, updated_at
FROM chat_schema.messages
WHERE conversation_id = $1
  AND is_deleted = FALSE
  AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListMessagesParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	CreatedAt      time.Time `json:"created_at"`
	Limit          int32     `json:"limit"`
}

// Cursor-based pagination: fetch messages older than the cursor timestamp
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ChatSchemaMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSchemaMessage{}
	for rows.Next() {
		var i ChatSchemaMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.IsEdited,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesInitial = `-- name: ListMessagesInitial :many
SELECT id, conversation_id, sender_id, content, is_edited, is_deleted, created_at, updated_at
FROM chat_schema.messages
WHERE conversation_id = $1
  AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $2
`

type ListMessagesInitialParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
}

// First page: no cursor, just latest N messages
func (q *Queries) ListMessagesInitial(ctx context.Context, arg ListMessagesInitialParams) ([]ChatSchemaMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesInitial, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSchemaMessage{}
	for rows.Next() {
		var i ChatSchemaMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.IsEdited,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE chat_schema.messages
SET is_deleted = TRUE, content = '', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, id)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE chat_schema.messages
SET content = $2, is_edited = TRUE, updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, conversation_id, sender_id, content, is_edited, is_deleted, created_at, updated_at
`

type UpdateMessageContentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (ChatSchemaMessage, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i ChatSchemaMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
